<?php error_reporting(0);?>

<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>RunCulator</title>



    <link rel="apple-touch-icon" sizes="180x180" href="_images/favicon/apple-touch-icon.png">
    <link rel="icon" type="_images/favicon/png" sizes="32x32" href="_images/favicon/favicon-32x32.png">
    <link rel="icon" type="_images/png" sizes="16x16" href="_images/favicon/favicon-16x16.png">
    <link rel="manifest" href="_images/favicon/site.webmanifest">
    <link rel="mask-icon" href="_images/favicon/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

    <!-- Bootstrap ORIGINAL -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="_javascript/picker.js"></script>

    <link href="https://fonts.googleapis.com/css?family=Righteous" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="css/pace2.css" rel="stylesheet" type="text/css" >



<?php include_once("_includes/analytics.php") ?>
</head>

<body background="_images/background.jpg" style="background-size:cover">

<?php include("_includes/navigation.php") ?>

<!-- HEADING TITLE !----------------------->
<div id="parent_container">
   <h1 id="pace_title"style="text-align: center;  text-shadow: 2px 2px #0099ff;"> Sports Calculator</h1>



      <div id="child_container"
       style="
        margin:auto;  border: 4px solid #0099ff; background:white;
        border-radius: 30px 10px;
        background-color: rgb(0, 0, 0);
        /* RGBa with 0.6 opacity */
        background-color: rgba(0, 0, 0, 0.6);
        /* For IE 5.5 - 7*/
        filter:progid:DXImageTransform.Microsoft.gradient(startColorstr=#99000000, endColorstr=#99000000);
        /* For IE 8*/
        -ms-filter: "progid:DXImageTransform.Microsoft.gradient(startColorstr=#99000000, endColorstr=#99000000)";
       ">

<div style="padding:5px 0 0px 15px">
  <div id="Home" style="margin-left:20px; margin-right:20px;color:#F0FFFF">

  <!--Privacy Statement-->
    <h1 style="padding:30px 0 0px 0">Privacy Statement</h1>
    <h2 style="padding:30px 0 10px 0">General</h2>
    <p>Your personal data is processed by us only in accordance with the provisions of German data privacy laws. The following provisions describe the type, scope and purpose of collecting, processing and utilizing personal data. This data privacy policy applies only to our web pages. If links on our pages route you to other pages, please inquire there about how your data are handled in such cases.</p>

    <!--Inventory data-->
    <h2 style="padding:30px 0 10px 0">Inventory data</h2>
    <p>
    (1) Your personal data, insofar as these are necessary for this contractual relationship (inventory data) in terms of its establishment, organization of content and modifications, are used exclusively for fulfilling the contract. For goods to be delivered, for instance, your name and address must be relayed to the supplier of the goods. </span>
    </p>
    (2) Without your explicit consent or a legal basis, your personal data are not passed on to third parties outside the scope of fulfilling this contract. After completion of the contract, your data are blocked against further use. After expiry of deadlines as per tax-related and commercial regulations, these data are deleted unless you have expressly consented to their further use.</span>

    <!--Web analysis with Google Analytics-->
    <h2 style="padding:30px 0 10px 0">Web analysis with Google Analytics</h2>

    This website uses Google Analytics, a web analysis service of Google Inc. (Google). Google Analytics uses cookies, i.e. text files stored on your computer to enable analysis of website usage by you. Information generated by the cookie about your use of this website is usually transmitted to a Google server in the United States and stored there. In case of activated IP anonymization on this website, however, your IP address is previously truncated by Google within member states of the European Union or in other states which are party to the agreement on the European Economic Area. Only in exceptional cases is a full IP address transmitted to a Google server in the United States and truncated there. On behalf this website's owner, Google will use this information to evaluate your use of the website, compile reports about website activities, and provide the website's operator with further services related to website and Internet usage. The IP address sent from your browser as part of Google Analytics is not merged with other data by Google. You can prevent storage of cookies by appropriately setting your browser software; in this case, however, please note that you might not be able to fully use all functions offered by this website. In addition, you can prevent data generated by the cookie and relating to your use of the website (including your IP address) from being collected and processed by Google, by downloading and installing a browser plug-in from the following link: <a href="http://tools.google.com/dlpage/gaoptout?hl=en" target="_blank">http://tools.google.com/dlpage/gaoptout?hl=en</a><br/>

    <!--Information about cookies-->
    <h2 style="padding:30px 0 10px 0">Information about cookies</h2>
    (1) To optimize our web presence, we use cookies. These are small text files stored in your computer's main memory. These cookies are deleted after you close the browser. Other cookies remain on your computer (long-term cookies) and permit its recognition on your next visit. This allows us to improve your access to our site.<br/>
    (2) You can prevent storage of cookies by choosing a &quot;disable cookies&quot; option in your browser settings. But this can limit the functionality of our Internet offers as a result.<br/>

    <!--Social plug-ins from Facebook-->
    <h2 style="padding:30px 0 10px 0">Social plug-ins from Facebook</h2>
    We use social plug-ins from facebook.com, operated by Facebook Inc., 1601 S. California Ave, Palo Alto, CA 94304, USA. The plug-ins can be recognized by way of the Facebook logo or the supplement &quot;Facebook Social Plug-in&quot;. For example, if you click on the &quot;Like&quot; button or leave a comment, the relevant information is transmitted directly from your browser to Facebook and stored there. Furthermore, Facebook makes your likes public for your Facebook friends. If you are logged into Facebook, it can assign the invocation of our page directly to your Facebook account. Even if you are not logged in or don't have a Facebook account, your browser sends information (e.g. which web pages you have called up, your IP address) which is then stored by Facebook. For details about handling of your personal data by Facebook and your related rights, please refer to the data privacy policy of Facebook: <a href="http://www.facebook.com/policy.php" target="_blank">http://www.facebook.com/policy.php</a>. If you do not want Facebook to map data collected about you via our Web sites to your Facebook account, you must log out of Facebook before you visit our web pages.<br/>

    <!--Social plug-ins from Twitter-->
    <h2 style="padding:30px 0 10px 0">Social plug-ins from Twitter</h2>
    With Twitter and its Retweet functions, we use social plug-ins from Twitter.com, operated by Twitter Inc. 795 Folsom St., Suite 600, San Francisco, CA 94107. If you use Retweet, the websites visited by you are announced to third parties and associated with your Twitter account. Details about handling of your data by Twitter as well as your rights and setting options for protecting your personal information can be found in Twitter's data privacy policy: <a href="http://twitter.com/privacy " target="_blank">http://twitter.com/privacy </a><br/>

    <!--Disclosure-->
    <h2 style="padding:30px 0 10px 0">Disclosure</h2><p style="margin-bottom:30px">According to the Federal Data Protection Act, you have a right to free-of-charge information about your stored data, and possibly entitlement to correction, blocking or deletion of such data. Inquiries can be directed to the following e-mail addresses: ( <a href="mailto:hello@RunCulator.com">hello@runculator.com</a> )</p><br/><br/>
  </div>
 </div>
 </div>




<?php include("_includes/footer.php") ?>
</body>
